--
--    Copyright 2010-2013 the original author or authors.
--
--    Licensed under the Apache License, Version 2.0 (the "License");
--    you may not use this file except in compliance with the License.
--    You may obtain a copy of the License at
--
--       http://www.apache.org/licenses/LICENSE-2.0
--
--    Unless required by applicable law or agreed to in writing, software
--    distributed under the License is distributed on an "AS IS" BASIS,
--    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
--    See the License for the specific language governing permissions and
--    limitations under the License.
--

CREATE TABLE Users (
    id int not null GENERATED BY DEFAULT AS IDENTITY,
    user_no varchar(8) not null,
    user_name varchar(32) not null,
    user_gender varchar(8) null,
    dep_id int not null,
    user_password varchar(128) not null,
    constraint PK_Users PRIMARY KEY (id)
);

CREATE TABLE Departments (
	id int not null GENERATED BY DEFAULT AS IDENTITY,
	dep_code varchar(16) not null,
	dep_name varchar(64) null,
	father_dep_id int not null,
	constraint PK_Departments PRIMARY KEY (id)
)

